config/routes.rb
Rails.application.routes.draw do
  get 'search', to:'search#index'
  resources :tags

    resources :comments do
    get 'search', on: :collection
  end

  devise_for :users
  
  resources :comments
  #get 'home/index'
  get 'home/about'
 # root'home#index'
  root'comments#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :tag
	belongs_to :user




	
	

	
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /comments or /comments.json
  def index
    @tags = Tag.all

    ta = params[:ta]

    if !ta.nil?
      @comments = Comment.where(tag_id: ta)
    else
      @comments = Comment.all
    end  
  end


  # GET /comments/1 or /comments/1.json


  def search
    @comments = Comment.where("comment LIKE?", "%" + params[:q] + "%")
  end



  def show
    @comment = Comment.find(params[:id])
  end

  # GET /comments/new
  def new
   # @comment = Comment.new
    @comment = current_user.comments.build
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments or /comments.json
  def create
    #@comment = Comment.create(comment_params)
     @comment = current_user.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
     #@comment = Comment.find(params[:id]
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    #@comment = Comment.find(params[:id]
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @comment = current_user.comments.find_by(id: params[:id])
    redirect_to comments_path, notice: "Not Authorised To Edit OR Destroy It!!" if @comment.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:first_name, :last_name, :comment, :tag_id, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  

  def index
   
  end
end
  

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
   
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy!

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:tag)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  
  <p>
    <%= comment.comment %>
  </p>

  

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First name" %>
  </div>
  <br></br>

  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last name"%>
  </div>
  <br></br>

  <div class="field form-group">
    <%= form.text_area :comment, class:"form-control", placeholder:"Leave your comment..." %>
  </div>
  <br></br>
 
  <div class="field form-group">
    <%= form.select :tag_id, Tag.all.map {|t| [t.tag,t.id]} %>
  


  <br></br>

<div class="field form-group">
    <%= form.number_field :user_id, id: :comment_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>


<br></br>

  <div>
    <%= form.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>
<br/>

<%= render "form", comment: @comment %>
<br>

<div>
  <%= link_to "Show this comment", @comment,  class:"btn btn-outline-success" %> 
  <%= link_to "Back to comments", comments_path,  class:"btn btn-outline-success" %>
</div>

app/views/comments/index.html.erb
<style>
  .center-heading {
    text-align: center;
  }
   
</style>

<div class="center-heading">
  <h1  style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: dodgerblue; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5)">Comments</h1>
</div>







<br/><br/>

<div class="p-3 bg-info bg-opacity-10 border border-info border-start-0 rounded-end">
 
<h5> Categories: <h5>


<div class="tags-container, tag-link, tag-link:hover">
   
      <% @tags.each do |tag| %>
        <%= link_to tag.tag, comments_path(:ta => tag.id) %>
      <% end %>
   
</div>


</div>

<br/><br/>

<% if user_signed_in? %>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Comment</th>
      <th>User Id</th>
      <th>Show</th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td>
          <%= comment.first_name %>
          <%= comment.last_name %></td>
        <td><%= render comment %></td>
        <td><%= comment.user_id %></td>
        <td><button type="button", class="btn btn-outline-primary" %>
           <%= link_to "Show ", comment %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New comment", new_comment_path, class:"btn btn-primary" %>

<% else %>
  <h1>Forum</h1>
Feel free to leave your comments...
<% end %>





  

app/views/comments/new.html.erb
<h1>Add New Comments</h1>
<br/>
<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path,  class:"btn btn-outline-success" %>
</div>

app/views/comments/search.html.erb
<% @comments.each do |comment| %>
  <div>
    <h3><%= comment.title %></h3>
    <!-- Additional thread details -->
  </div>
<% end %>

app/views/comments/show.html.erb
<div style="font-size: 40px; margin-bottom: 10px;", class="shadow-lg p-3 mb-5 bg-body-tertiary rounded">
  <%= @comment.comment %>
  <br/><br/>
  
</div>
<p class="text-end">Category: <%= @comment.tag.tag %>
</p>

<br> </br>


<div>
  <%= link_to "Edit", edit_comment_path(@comment), class:"btn btn-outline-primary btn-sm"%>

  

  <%= link_to "Back", comments_path, class:"btn btn-outline-primary btn-sm" %>
<div style="margin-top: 20px;">
  
  <%= button_to "Destroy", @comment, method: :delete, class:"btn btn-outline-warning btn-sm" %>
  
</div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
  	<%=link_to 'Forum App', root_path, class:"navbar-brand" %>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        
          
        

        

          <% if user_signed_in? %>

              <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
              
              </li>

              <li class="nav-item">
              <%= link_to "Edit Profile",  edit_user_registration_path, class:"nav-link"%>
              
              </li>

              <li class="nav-item">
              <%= link_to "Add Comments", new_comment_path, class:"nav-link"%>
          
              </li>
          <% else %>

              <li class="nav-item">
              <%= link_to "Sign Up",  new_user_registration_path, class:"nav-link"%>
              
            </li>

              <li class="nav-item">
              <%= link_to "Sign In",  new_user_session_path, class:"nav-link"%>
              
            </li>
          <% end %>





        
        
      </ul>
     


      
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us... </h1>

app/views/home/index.html.erb
<h1>Forum</h1>
Feel free to leave your comments...

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Forum App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'rails-ujs' %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
      <br/>

      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

    
      <%= yield %>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/search/_form.html.erb
<%= search_form_for(@q, url: search_path, method: :get, class: 'd-flex') do |f| %>

 
  
  <%= f.search_field :comments_i_cont_any, placeholder: "Search...", class:"form-control me-2" %>

  <%= f.submit "Search!", class:"btn btn-outline-success" %>
<% end %>

app/views/search/index.html.erb
<h1>Search Result</h1>

app/views/tags/_form.html.erb
<%= simple_form_for(@tag) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :tag %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <p>
    <strong>Tag:</strong>
    <%= tag.tag %>
  </p>

</div>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Show this tag", @tag %> |
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tags</h1>

<div id="tags">
  <% @tags.each do |tag| %>
    <%= render tag %>
    <p>
      <%= link_to "Show this tag", tag %>
    </p>
  <% end %>
</div>

<%= link_to "New tag", new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tag %>

<div>
  <%= link_to "Edit this tag", edit_tag_path(@tag) %> |
  <%= link_to "Back to tags", tags_path %>

  <%= button_to "Destroy this tag", @tag, method: :delete %>
</div>